# Generated by Django 3.0 on 2022-08-04 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_likepost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='likepost',
        ),
    ]
