# Generated by Django 3.0 on 2022-08-04 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_likepost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='number_likes',
            new_name='numbers_likes',
        ),
    ]
